//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the PTAMM_RGBD_cooperative package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __PTAMM_RGBD_cooperative__PTAMMPARAMSCONFIG_H__
#define __PTAMM_RGBD_cooperative__PTAMMPARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace PTAMM_RGBD_cooperative
{
  class PtammParamsConfigStatics;
  
  class PtammParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(PtammParamsConfig &config, const PtammParamsConfig &max, const PtammParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PtammParamsConfig &config1, const PtammParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PtammParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PtammParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PtammParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PtammParamsConfig &config) const = 0;
      virtual void getValue(const PtammParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T PtammParamsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (PtammParamsConfig::* field);

      virtual void clamp(PtammParamsConfig &config, const PtammParamsConfig &max, const PtammParamsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PtammParamsConfig &config1, const PtammParamsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PtammParamsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PtammParamsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PtammParamsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PtammParamsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PtammParamsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PtammParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PtammParamsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<PtammParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PtammParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Scale"==(*_i)->name){Scale = boost::any_cast<double>(val);}
        if("MaxPatchesPerFrame"==(*_i)->name){MaxPatchesPerFrame = boost::any_cast<double>(val);}
        if("MaxKFDistWiggleMult"==(*_i)->name){MaxKFDistWiggleMult = boost::any_cast<double>(val);}
        if("NoLevelZeroMapPoints"==(*_i)->name){NoLevelZeroMapPoints = boost::any_cast<bool>(val);}
        if("CoarseMin"==(*_i)->name){CoarseMin = boost::any_cast<double>(val);}
        if("CoarseMax"==(*_i)->name){CoarseMax = boost::any_cast<double>(val);}
        if("CoarseRange"==(*_i)->name){CoarseRange = boost::any_cast<double>(val);}
        if("CoarseSubPixIts"==(*_i)->name){CoarseSubPixIts = boost::any_cast<double>(val);}
        if("DisableCoarse"==(*_i)->name){DisableCoarse = boost::any_cast<bool>(val);}
        if("CoarseMinVelocity"==(*_i)->name){CoarseMinVelocity = boost::any_cast<double>(val);}
        if("TrackingQualityGood"==(*_i)->name){TrackingQualityGood = boost::any_cast<double>(val);}
        if("TrackingQualityLost"==(*_i)->name){TrackingQualityLost = boost::any_cast<double>(val);}
        if("MaxIterations"==(*_i)->name){MaxIterations = boost::any_cast<int>(val);}
        if("MaxKF"==(*_i)->name){MaxKF = boost::any_cast<int>(val);}
        if("BundleMethod"==(*_i)->name){BundleMethod = boost::any_cast<std::string>(val);}
        if("UpdateSquaredConvergenceLimit"==(*_i)->name){UpdateSquaredConvergenceLimit = boost::any_cast<double>(val);}
        if("FASTMethod"==(*_i)->name){FASTMethod = boost::any_cast<std::string>(val);}
        if("Thres_lvl0"==(*_i)->name){Thres_lvl0 = boost::any_cast<int>(val);}
        if("Thres_lvl1"==(*_i)->name){Thres_lvl1 = boost::any_cast<int>(val);}
        if("Thres_lvl2"==(*_i)->name){Thres_lvl2 = boost::any_cast<int>(val);}
        if("Thres_lvl3"==(*_i)->name){Thres_lvl3 = boost::any_cast<int>(val);}
        if("AdaptiveThrs"==(*_i)->name){AdaptiveThrs = boost::any_cast<bool>(val);}
        if("AdaptiveThrsMult"==(*_i)->name){AdaptiveThrsMult = boost::any_cast<double>(val);}
        if("RotationEstimatorBlur"==(*_i)->name){RotationEstimatorBlur = boost::any_cast<double>(val);}
        if("UseRotationEstimator"==(*_i)->name){UseRotationEstimator = boost::any_cast<bool>(val);}
        if("MiniPatchMaxSSD"==(*_i)->name){MiniPatchMaxSSD = boost::any_cast<int>(val);}
        if("PlaneAlignerRansacs"==(*_i)->name){PlaneAlignerRansacs = boost::any_cast<int>(val);}
        if("RelocMaxScore"==(*_i)->name){RelocMaxScore = boost::any_cast<int>(val);}
        if("MaxStereoInitLoops"==(*_i)->name){MaxStereoInitLoops = boost::any_cast<int>(val);}
      }
    }

    double Scale;
double MaxPatchesPerFrame;
double MaxKFDistWiggleMult;
bool NoLevelZeroMapPoints;
double CoarseMin;
double CoarseMax;
double CoarseRange;
double CoarseSubPixIts;
bool DisableCoarse;
double CoarseMinVelocity;
double TrackingQualityGood;
double TrackingQualityLost;
int MaxIterations;
int MaxKF;
std::string BundleMethod;
double UpdateSquaredConvergenceLimit;
std::string FASTMethod;
int Thres_lvl0;
int Thres_lvl1;
int Thres_lvl2;
int Thres_lvl3;
bool AdaptiveThrs;
double AdaptiveThrsMult;
double RotationEstimatorBlur;
bool UseRotationEstimator;
int MiniPatchMaxSSD;
int PlaneAlignerRansacs;
int RelocMaxScore;
int MaxStereoInitLoops;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Scale;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double MaxPatchesPerFrame;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double MaxKFDistWiggleMult;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool NoLevelZeroMapPoints;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double CoarseMin;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double CoarseMax;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double CoarseRange;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double CoarseSubPixIts;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool DisableCoarse;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double CoarseMinVelocity;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double TrackingQualityGood;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double TrackingQualityLost;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int MaxIterations;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int MaxKF;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      std::string BundleMethod;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double UpdateSquaredConvergenceLimit;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      std::string FASTMethod;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int Thres_lvl0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int Thres_lvl1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int Thres_lvl2;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int Thres_lvl3;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool AdaptiveThrs;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double AdaptiveThrsMult;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double RotationEstimatorBlur;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool UseRotationEstimator;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int MiniPatchMaxSSD;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int PlaneAlignerRansacs;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int RelocMaxScore;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int MaxStereoInitLoops;
//#line 255 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PtammParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PtammParamsConfig &__max__ = __getMax__();
      const PtammParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PtammParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PtammParamsConfig &__getDefault__();
    static const PtammParamsConfig &__getMax__();
    static const PtammParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const PtammParamsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void PtammParamsConfig::ParamDescription<std::string>::clamp(PtammParamsConfig &config, const PtammParamsConfig &max, const PtammParamsConfig &min) const
  {
    return;
  }

  class PtammParamsConfigStatics
  {
    friend class PtammParamsConfig;
    
    PtammParamsConfigStatics()
    {
PtammParamsConfig::GroupDescription<PtammParamsConfig::DEFAULT, PtammParamsConfig> Default("Default", "", 0, 0, true, &PtammParamsConfig::groups);
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Scale = 0.01;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Scale = 30.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Scale = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("Scale", "double", 0, "Scale", "", &PtammParamsConfig::Scale)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("Scale", "double", 0, "Scale", "", &PtammParamsConfig::Scale)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.MaxPatchesPerFrame = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.MaxPatchesPerFrame = 1000.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.MaxPatchesPerFrame = 1000.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("MaxPatchesPerFrame", "double", 0, "max features per frame", "", &PtammParamsConfig::MaxPatchesPerFrame)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("MaxPatchesPerFrame", "double", 0, "max features per frame", "", &PtammParamsConfig::MaxPatchesPerFrame)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.MaxKFDistWiggleMult = 0.1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.MaxKFDistWiggleMult = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.MaxKFDistWiggleMult = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("MaxKFDistWiggleMult", "double", 0, "'distance' after which a new kf is requested", "", &PtammParamsConfig::MaxKFDistWiggleMult)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("MaxKFDistWiggleMult", "double", 0, "'distance' after which a new kf is requested", "", &PtammParamsConfig::MaxKFDistWiggleMult)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.NoLevelZeroMapPoints = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.NoLevelZeroMapPoints = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.NoLevelZeroMapPoints = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<bool>("NoLevelZeroMapPoints", "bool", 0, "do not add map points at level zero", "", &PtammParamsConfig::NoLevelZeroMapPoints)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<bool>("NoLevelZeroMapPoints", "bool", 0, "do not add map points at level zero", "", &PtammParamsConfig::NoLevelZeroMapPoints)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.CoarseMin = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.CoarseMin = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.CoarseMin = 20.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("CoarseMin", "double", 0, "min number of features for coarse tracking", "", &PtammParamsConfig::CoarseMin)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("CoarseMin", "double", 0, "min number of features for coarse tracking", "", &PtammParamsConfig::CoarseMin)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.CoarseMax = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.CoarseMax = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.CoarseMax = 60.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("CoarseMax", "double", 0, "max number of features for coarse tracking", "", &PtammParamsConfig::CoarseMax)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("CoarseMax", "double", 0, "max number of features for coarse tracking", "", &PtammParamsConfig::CoarseMax)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.CoarseRange = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.CoarseRange = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.CoarseRange = 30.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("CoarseRange", "double", 0, "Pixel search radius for coarse features", "", &PtammParamsConfig::CoarseRange)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("CoarseRange", "double", 0, "Pixel search radius for coarse features", "", &PtammParamsConfig::CoarseRange)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.CoarseSubPixIts = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.CoarseSubPixIts = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.CoarseSubPixIts = 8.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("CoarseSubPixIts", "double", 0, "coarse tracking sub-pixel iterations", "", &PtammParamsConfig::CoarseSubPixIts)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("CoarseSubPixIts", "double", 0, "coarse tracking sub-pixel iterations", "", &PtammParamsConfig::CoarseSubPixIts)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.DisableCoarse = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.DisableCoarse = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.DisableCoarse = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<bool>("DisableCoarse", "bool", 0, "enable/disable coarse tracking", "", &PtammParamsConfig::DisableCoarse)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<bool>("DisableCoarse", "bool", 0, "enable/disable coarse tracking", "", &PtammParamsConfig::DisableCoarse)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.CoarseMinVelocity = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.CoarseMinVelocity = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.CoarseMinVelocity = 0.006;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("CoarseMinVelocity", "double", 0, "speed above which coarse stage is used", "", &PtammParamsConfig::CoarseMinVelocity)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("CoarseMinVelocity", "double", 0, "speed above which coarse stage is used", "", &PtammParamsConfig::CoarseMinVelocity)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.TrackingQualityGood = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.TrackingQualityGood = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.TrackingQualityGood = 0.3;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("TrackingQualityGood", "double", 0, "min ratio features visible/features found for good tracking", "", &PtammParamsConfig::TrackingQualityGood)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("TrackingQualityGood", "double", 0, "min ratio features visible/features found for good tracking", "", &PtammParamsConfig::TrackingQualityGood)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.TrackingQualityLost = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.TrackingQualityLost = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.TrackingQualityLost = 0.13;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("TrackingQualityLost", "double", 0, "max ratio features visible/features found before lost", "", &PtammParamsConfig::TrackingQualityLost)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("TrackingQualityLost", "double", 0, "max ratio features visible/features found before lost", "", &PtammParamsConfig::TrackingQualityLost)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.MaxIterations = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.MaxIterations = 100;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.MaxIterations = 20;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("MaxIterations", "int", 0, "max iterations for bundle adjustment", "", &PtammParamsConfig::MaxIterations)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("MaxIterations", "int", 0, "max iterations for bundle adjustment", "", &PtammParamsConfig::MaxIterations)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.MaxKF = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.MaxKF = 1000;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.MaxKF = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("MaxKF", "int", 0, "number of keyframes kept in the map (0 or 1 = inf)", "", &PtammParamsConfig::MaxKF)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("MaxKF", "int", 0, "number of keyframes kept in the map (0 or 1 = inf)", "", &PtammParamsConfig::MaxKF)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.BundleMethod = "";
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.BundleMethod = "";
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.BundleMethod = "LOCAL_GLOBAL";
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<std::string>("BundleMethod", "str", 0, "bundleadjustment method", "{'enum_description': 'An enum to set the bundle adjustment mode.', 'enum': [{'srcline': 15, 'description': 'local and global bundle adjustment', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'LOCAL_GLOBAL', 'ctype': 'std::string', 'type': 'str', 'name': 'LOCAL_GLOBAL'}, {'srcline': 16, 'description': 'local bundle adjustment only', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'LOCAL', 'ctype': 'std::string', 'type': 'str', 'name': 'LOCAL'}, {'srcline': 17, 'description': 'global bundle adjustment only', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'GLOBAL', 'ctype': 'std::string', 'type': 'str', 'name': 'GLOBAL'}]}", &PtammParamsConfig::BundleMethod)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<std::string>("BundleMethod", "str", 0, "bundleadjustment method", "{'enum_description': 'An enum to set the bundle adjustment mode.', 'enum': [{'srcline': 15, 'description': 'local and global bundle adjustment', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'LOCAL_GLOBAL', 'ctype': 'std::string', 'type': 'str', 'name': 'LOCAL_GLOBAL'}, {'srcline': 16, 'description': 'local bundle adjustment only', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'LOCAL', 'ctype': 'std::string', 'type': 'str', 'name': 'LOCAL'}, {'srcline': 17, 'description': 'global bundle adjustment only', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'GLOBAL', 'ctype': 'std::string', 'type': 'str', 'name': 'GLOBAL'}]}", &PtammParamsConfig::BundleMethod)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.UpdateSquaredConvergenceLimit = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.UpdateSquaredConvergenceLimit = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.UpdateSquaredConvergenceLimit = 1e-06;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("UpdateSquaredConvergenceLimit", "double", 0, "limit for convergence in bundle adjustment", "", &PtammParamsConfig::UpdateSquaredConvergenceLimit)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("UpdateSquaredConvergenceLimit", "double", 0, "limit for convergence in bundle adjustment", "", &PtammParamsConfig::UpdateSquaredConvergenceLimit)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.FASTMethod = "";
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.FASTMethod = "";
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.FASTMethod = "FAST9";
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<std::string>("FASTMethod", "str", 0, "FAST corner method", "{'enum_description': 'An enum to set the FAST corner extraction method.', 'enum': [{'srcline': 21, 'description': 'FAST 9', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST9', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST9'}, {'srcline': 22, 'description': 'FAST 10', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST10', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST10'}, {'srcline': 23, 'description': 'FAST 9 with nonmax suppression', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST9_nonmax', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST9_nonmax'}, {'srcline': 24, 'description': 'AGAST 12 pixel diamond', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'AGAST12d', 'ctype': 'std::string', 'type': 'str', 'name': 'AGAST12d'}, {'srcline': 25, 'description': 'AGAST 16 pixel circular', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'OAST16', 'ctype': 'std::string', 'type': 'str', 'name': 'OAST16'}]}", &PtammParamsConfig::FASTMethod)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<std::string>("FASTMethod", "str", 0, "FAST corner method", "{'enum_description': 'An enum to set the FAST corner extraction method.', 'enum': [{'srcline': 21, 'description': 'FAST 9', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST9', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST9'}, {'srcline': 22, 'description': 'FAST 10', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST10', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST10'}, {'srcline': 23, 'description': 'FAST 9 with nonmax suppression', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST9_nonmax', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST9_nonmax'}, {'srcline': 24, 'description': 'AGAST 12 pixel diamond', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'AGAST12d', 'ctype': 'std::string', 'type': 'str', 'name': 'AGAST12d'}, {'srcline': 25, 'description': 'AGAST 16 pixel circular', 'srcfile': '../cfg/PtammParams.cfg', 'cconsttype': 'const char * const', 'value': 'OAST16', 'ctype': 'std::string', 'type': 'str', 'name': 'OAST16'}]}", &PtammParamsConfig::FASTMethod)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Thres_lvl0 = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Thres_lvl0 = 255;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Thres_lvl0 = 10;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("Thres_lvl0", "int", 0, "threshold for FAST features on level 0", "", &PtammParamsConfig::Thres_lvl0)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("Thres_lvl0", "int", 0, "threshold for FAST features on level 0", "", &PtammParamsConfig::Thres_lvl0)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Thres_lvl1 = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Thres_lvl1 = 255;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Thres_lvl1 = 15;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("Thres_lvl1", "int", 0, "threshold for FAST features on level 1", "", &PtammParamsConfig::Thres_lvl1)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("Thres_lvl1", "int", 0, "threshold for FAST features on level 1", "", &PtammParamsConfig::Thres_lvl1)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Thres_lvl2 = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Thres_lvl2 = 255;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Thres_lvl2 = 15;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("Thres_lvl2", "int", 0, "threshold for FAST features on level 2", "", &PtammParamsConfig::Thres_lvl2)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("Thres_lvl2", "int", 0, "threshold for FAST features on level 2", "", &PtammParamsConfig::Thres_lvl2)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Thres_lvl3 = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Thres_lvl3 = 255;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Thres_lvl3 = 10;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("Thres_lvl3", "int", 0, "threshold for FAST features on level 3", "", &PtammParamsConfig::Thres_lvl3)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("Thres_lvl3", "int", 0, "threshold for FAST features on level 3", "", &PtammParamsConfig::Thres_lvl3)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.AdaptiveThrs = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.AdaptiveThrs = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.AdaptiveThrs = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<bool>("AdaptiveThrs", "bool", 0, "adaptive threshold for corner extraction", "", &PtammParamsConfig::AdaptiveThrs)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<bool>("AdaptiveThrs", "bool", 0, "adaptive threshold for corner extraction", "", &PtammParamsConfig::AdaptiveThrs)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.AdaptiveThrsMult = 0.5;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.AdaptiveThrsMult = 20.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.AdaptiveThrsMult = 5.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("AdaptiveThrsMult", "double", 0, "controls adaptive threshold to MaxPatches*N corners", "", &PtammParamsConfig::AdaptiveThrsMult)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("AdaptiveThrsMult", "double", 0, "controls adaptive threshold to MaxPatches*N corners", "", &PtammParamsConfig::AdaptiveThrsMult)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.RotationEstimatorBlur = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.RotationEstimatorBlur = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.RotationEstimatorBlur = 0.75;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("RotationEstimatorBlur", "double", 0, "small images for the rotation estimator blur", "", &PtammParamsConfig::RotationEstimatorBlur)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<double>("RotationEstimatorBlur", "double", 0, "small images for the rotation estimator blur", "", &PtammParamsConfig::RotationEstimatorBlur)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.UseRotationEstimator = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.UseRotationEstimator = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.UseRotationEstimator = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<bool>("UseRotationEstimator", "bool", 0, "small images for the rotation estimator enable/disable", "", &PtammParamsConfig::UseRotationEstimator)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<bool>("UseRotationEstimator", "bool", 0, "small images for the rotation estimator enable/disable", "", &PtammParamsConfig::UseRotationEstimator)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.MiniPatchMaxSSD = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.MiniPatchMaxSSD = 10000000;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.MiniPatchMaxSSD = 100000;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("MiniPatchMaxSSD", "int", 0, "MiniPatch tracking threshhold", "", &PtammParamsConfig::MiniPatchMaxSSD)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("MiniPatchMaxSSD", "int", 0, "MiniPatch tracking threshhold", "", &PtammParamsConfig::MiniPatchMaxSSD)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.PlaneAlignerRansacs = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.PlaneAlignerRansacs = 1000;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.PlaneAlignerRansacs = 100;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("PlaneAlignerRansacs", "int", 0, "number of dominant plane RANSACs", "", &PtammParamsConfig::PlaneAlignerRansacs)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("PlaneAlignerRansacs", "int", 0, "number of dominant plane RANSACs", "", &PtammParamsConfig::PlaneAlignerRansacs)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.RelocMaxScore = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.RelocMaxScore = 90000000;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.RelocMaxScore = 9000000;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("RelocMaxScore", "int", 0, "score for relocalization", "", &PtammParamsConfig::RelocMaxScore)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("RelocMaxScore", "int", 0, "score for relocalization", "", &PtammParamsConfig::RelocMaxScore)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.MaxStereoInitLoops = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.MaxStereoInitLoops = 100;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.MaxStereoInitLoops = 10;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("MaxStereoInitLoops", "int", 0, "max # of loops for stereo initialization", "", &PtammParamsConfig::MaxStereoInitLoops)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(PtammParamsConfig::AbstractParamDescriptionConstPtr(new PtammParamsConfig::ParamDescription<int>("MaxStereoInitLoops", "int", 0, "max # of loops for stereo initialization", "", &PtammParamsConfig::MaxStereoInitLoops)));
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(PtammParamsConfig::AbstractGroupDescriptionConstPtr(new PtammParamsConfig::GroupDescription<PtammParamsConfig::DEFAULT, PtammParamsConfig>(Default)));
//#line 390 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<PtammParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<PtammParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PtammParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PtammParamsConfig __max__;
    PtammParamsConfig __min__;
    PtammParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PtammParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PtammParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PtammParamsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const PtammParamsConfig &PtammParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const PtammParamsConfig &PtammParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const PtammParamsConfig &PtammParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<PtammParamsConfig::AbstractParamDescriptionConstPtr> &PtammParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PtammParamsConfig::AbstractGroupDescriptionConstPtr> &PtammParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PtammParamsConfigStatics *PtammParamsConfig::__get_statics__()
  {
    const static PtammParamsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PtammParamsConfigStatics::get_instance();
    
    return statics;
  }

//#line 15 "../cfg/PtammParams.cfg"
      const char * const PtammParams_LOCAL_GLOBAL = "LOCAL_GLOBAL";
//#line 16 "../cfg/PtammParams.cfg"
      const char * const PtammParams_LOCAL = "LOCAL";
//#line 17 "../cfg/PtammParams.cfg"
      const char * const PtammParams_GLOBAL = "GLOBAL";
//#line 21 "../cfg/PtammParams.cfg"
      const char * const PtammParams_FAST9 = "FAST9";
//#line 22 "../cfg/PtammParams.cfg"
      const char * const PtammParams_FAST10 = "FAST10";
//#line 23 "../cfg/PtammParams.cfg"
      const char * const PtammParams_FAST9_nonmax = "FAST9_nonmax";
//#line 24 "../cfg/PtammParams.cfg"
      const char * const PtammParams_AGAST12d = "AGAST12d";
//#line 25 "../cfg/PtammParams.cfg"
      const char * const PtammParams_OAST16 = "OAST16";
//#line 29 "../cfg/PtammParams.cfg"
      const char * const PtammParams_MM_CONSTANT = "CONSTANT";
//#line 30 "../cfg/PtammParams.cfg"
      const char * const PtammParams_MM_IMU = "IMU";
//#line 31 "../cfg/PtammParams.cfg"
      const char * const PtammParams_MM_FULL_POSE = "FULL_POSE";
//#line 34 "../cfg/PtammParams.cfg"
      const int PtammParams_SEND_PARAMETERS = 1;
}

#endif // __PTAMMPARAMSRECONFIGURATOR_H__
